#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'PoseTranspose','console_scripts','PoseTransposeNode'
__requires__ = 'PoseTranspose'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('PoseTranspose', 'console_scripts', 'PoseTransposeNode')()
    )
